package Model;

public enum STATE {
	NULL, 
	WAITING_GOOD_NAME, WAITING_GOOD_DESCRIPTION, WAITING_GOOD_CODE,
	WAITING_LOCAL_NAME, WAITING_LOCAL_DESCRIPTION,
	WAITING_CATEGORY_NAME, WAITING_CATEGORY_DESCRIPTION, WAITING_CATEGORY_CODE,
	LIST_LOCATIONS, LIST_CATEGORIES, LIST_GOODS_BY_LOCATION,
	WAITING_LOCATION, WAITING_CATEGORY,
	WAITING_GOOD_BY_CODE, WAITING_GOOD_BY_NAME, WAITING_GOOD_BY_DESCRIPTION;
}
